### PR TITLE
laravel 8 support

### PR DESCRIPTION
**Pull request by reliq**

### CODE REVIEW

**Comment by mohamedsabil83** [comment]
Hey, any news with this PR? we need it in our new project.

**Comment by francoism90** [comment]
Please merge, I would like to upgrade to Laravel 8. :)

**Comment by cyrildewit** [comment]
Hey @reliq ,

Thank you for working on this pull request. I couldn't merge it, unfortunately, because of a few reasons:
- New minimum PHP version
- Tests weren't running for older Laravel versions

I assume you were thinking about releasing a new major release, but fortunately, there aren't any breaking changes between these Laravel versions for this package.

**Comment by reliq** [comment]
OK @cyrildewit. Thank you!

**Pull request closed without merging**
