### PR TITLE
Release v5.0.0

### PR DESCRIPTION
**Pull request by cyrildewit**
Roadmap #170 

## Todo

- [x] Update changelog
- [x] Update upgrading

### CODE REVIEW

**Comment by cyrildewit** [comment]
@zefexdeveloper @francoism90 

I'm rounding off for the release of v5.0.0 and would like to receive some feedback about it. The biggest change I'm worried about is the refactoring of `useVisitor` and `useIpAddress`. If you want to update these values, you will have to create your own `Visitor` class in the new version. But I wonder if this method coverages all use cases. 

The readme is partially updated and the upgrade guide has also been updated.

I've released a second alpha release `v5.0.0-alpha.1`.

**Comment by francoism90** [comment]
@cyrildewit Thanks for creating a new release!

So far I've tested the v5.0.0, and didn't found any major issues. I didn't tested the new Visitor class, but it looks promising. Maybe you should extend the given example with an actually use case? :)

```
/**
     * Get the unique ID that represent's the visitor.
     *
     * @return string
     */
    public function id(): string {
        return auth()->user()->id; // or whatever user id handler..
    }
```
Maybe something better instead of using the generated cookie/session value?

Please note I'm just a simple user and don't run your package on production either. ;)
Maybe someone else can provide more helpful feedback, but it looks OK to me and performs really well.

**Comment by cyrildewit** [comment]
@francoism90 thank you for the feedback.

> Maybe you should extend the given example with an actually use case?

Good idea! Looking into it.

**Comment by zefexdeveloper** [comment]
That you for this, sorry that I didn't answer before, I'm really busy and this COVID19 thing is going crazy.

**Pull request merged**
