### PR TITLE
support laravel 9

### PR DESCRIPTION
**Pull request by atmonshi**
support laravel 9

### CODE REVIEW

**Comment by AbdallaMohammed** [comment]
@cyrildewit can you review and merge this?

**Comment by paranarimasu** [comment]
Hello @atmonshi 👋 I wasn't able to send this your way directly, but IMO the workflow for tests should be updated as well here:

<https://github.com/cyrildewit/eloquent-viewable/compare/master...paranarimasu:laravel-9>

**Comment by atmonshi** [comment]
thanks, @paranarimasu,
I also added `laravel/legacy-factories` to `require-dev` and now all the test works.

@cyrildewit I hope this gets merged soon.

**Comment by cyrildewit** [comment]
@atmonshi @paranarimasu Thank you for your work on this. I've merged it and it's released under the tag v6.1.0 I didn't have any time to work on this.

**Pull request merged**
